[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
bytes = "1.8.0"
console-subscriber = "0.4.1"
futures = "0.3.31"
reqwest = "0.12.9"
shadow-clone = "1.2.1"
text_io = "0.1.12"
tokio = { version = "1.41.0", features = ["full"] }
tracing = "0.1.40"
warp = "0.3.7"
webrtc = { path = "../webrtc" }
